### ISSUE TITLE
differentiate jump label to jump function

### ISSUE THREAD

**Issue by pirpyn** [pirpyn/gdb-syntax-vscode#32]
Currently jump rendering only accept direct NUM or offset but, no named label, nor computed offset like $_+0x123
Thats because i don't know how to differentiate jump label from jump function

**Comment by GitMensch** [comment]
There is no way to differentiate between that if used "alone". From my experience:

jump/until/break SOME

will do that on the SOME label, if it occurs in the current function, otherwise will try a function with that name and if not found (only with break) create (depending on setting and possible user check) a pending breakpoint to a "not yet known" function SOME.

jump/until/break address

can always point to anything, both "direct" and if the address is resolved by arithmetic (or de-referencing a variable)
Similar with

jump/until/break +15   # or -10

**Comment by pirpyn** [comment]
wont fix this issue.

**Comment by GitMensch** [comment]
Can you please reclose as "not planned"?

**Comment by pirpyn** [comment]
There's not such label in GitHub by default. And although I agree won't fix is not the same as not planned semantically, I don't feel the need for this new label.

**Comment by GitMensch** [comment]
Oh, there is an issue state since some months:

![close](https://github.com/pirpyn/gdb-syntax-vscode/assets/6699539/3131817a-9f19-4d8d-9888-50e3d8550668)
![reclose](https://github.com/pirpyn/gdb-syntax-vscode/assets/6699539/a1980d87-6145-4308-af0d-9d4a1ce9a5ba)

**Comment by pirpyn** [comment]
Did not saw that
